name = "FiveBoxModel"
uuid = "1ed0f041-dc51-4d38-a6e7-d31254afd2bd"
authors = ["Daniel Pals <Daniel.Pals@tum.de>"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
