name = "FiveBoxModel"
uuid = "1ed0f041-dc51-4d38-a6e7-d31254afd2bd"
authors = ["Daniel Pals <Daniel.Pals@tum.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
